# Windows (https://github.com/travis-ci-tester/toolchain-table)

environment:
  matrix:
#   FIXME: no support yet in windows for odb in hunter
#        * autotools project is not supported by Visual Studio
#        * mingw is failing for reasons yet to be investigated
    - TOOLCHAIN: "dummy"
      PROJECT_DIR: examples\odb-mysql

#    FIXME:
#    * https://ci.appveyor.com/project/ingenue/hunter/build/1.0.179/job/odk76l8hwphkslj6
#    - TOOLCHAIN: "default"
#      PROJECT_DIR: examples\odb-mysql
#
#    FIXME:
#    * https://ci.appveyor.com/project/ingenue/hunter/build/1.0.179/job/9e6jdvvgey14qm0u
#    - TOOLCHAIN: "ninja-vs-12-2013-win64"
#      PROJECT_DIR: examples\odb-mysql
#
#    FIXME:
#    * https://ci.appveyor.com/project/ingenue/hunter/build/1.0.179/job/p6d2x9w7kin8o5k4
#    - TOOLCHAIN: "nmake-vs-12-2013-win64"
#      PROJECT_DIR: examples\odb-mysql
#
#    FIXME:
#    * https://ci.appveyor.com/project/ingenue/hunter/build/1.0.179/job/c8fv2lhwf8itx882
#    - TOOLCHAIN: "nmake-vs-12-2013"
#      PROJECT_DIR: examples\odb-mysql
#
#    FIXME:
#    * https://ci.appveyor.com/project/ingenue/hunter/build/1.0.179/job/k6xw31ger7jbkfgo
#    - TOOLCHAIN: "vs-10-2010"
#      PROJECT_DIR: examples\odb-mysql
#
#    FIXME:
#    * https://ci.appveyor.com/project/ingenue/hunter/build/1.0.179/job/8lwm34rrcncwadup
#    - TOOLCHAIN: "vs-11-2012"
#      PROJECT_DIR: examples\odb-mysql
#
#    FIXME:
#    * https://ci.appveyor.com/project/ingenue/hunter/build/1.0.179/job/sxh8ylvwup2nftmq
#    - TOOLCHAIN: "vs-12-2013-win64"
#      PROJECT_DIR: examples\odb-mysql
#
#    FIXME:
#    * https://ci.appveyor.com/project/ingenue/hunter/build/1.0.179/job/r9nq56fvkbhu1b07
#    - TOOLCHAIN: "vs-12-2013-xp"
#      PROJECT_DIR: examples\odb-mysql
#
#    FIXME:
#    * https://ci.appveyor.com/project/ingenue/hunter/build/1.0.179/job/1k7d0844d0crv8xo
#    - TOOLCHAIN: "vs-12-2013"
#      PROJECT_DIR: examples\odb-mysql
#
#    FIXME:
#    * https://ci.appveyor.com/project/ingenue/hunter/build/1.0.179/job/ygtnv39knd26qpm6
#    - TOOLCHAIN: "vs-14-2015"
#      PROJECT_DIR: examples\odb-mysql
#
#    FIXME:
#    * https://ci.appveyor.com/project/ingenue/hunter/build/1.0.179/job/fr0xh174ivr3wjyb
#    - TOOLCHAIN: "vs-9-2008"
#      PROJECT_DIR: examples\odb-mysql
#
#    FIXME:
#    * https://ci.appveyor.com/project/ingenue/hunter/build/1.0.179/job/x3udsdmvi2bsy09t
#    - TOOLCHAIN: "mingw"
#      PROJECT_DIR: examples\odb-mysql

install:
  - git submodule update --init --recursive

  # Install ninja
  - cmd: set NINJA_VERSION="1.6.0"
  - cmd: appveyor DownloadFile "https://github.com/ninja-build/ninja/releases/download/v%NINJA_VERSION%/ninja-win.zip"
  - cmd: cmake -E tar xf "ninja-win.zip"
  - cmd: cmake -E make_directory "ninja"
  - cmd: cmake -E rename "ninja.exe" "ninja/ninja.exe"
  - cmd: set PATH=%cd%\ninja;%PATH%

  # Remove entry with sh.exe from PATH to fix error with MinGW toolchain
  # (For MinGW make to work correctly sh.exe must NOT be in your path)
  # * http://stackoverflow.com/a/3870338/2288008
  - cmd: set PATH=%PATH:C:\Program Files\Git\usr\bin;=%

  # Use MinGW from Qt tools because version is higher
  # * http://www.appveyor.com/docs/installed-software#qt
  - cmd: set MINGW_PATH=C:\Qt\Tools\mingw492_32\bin

  # Install Polly toolchains
  - cmd: set POLLY_VERSION=0.9.0
  - cmd: appveyor DownloadFile "https://github.com/ruslo/polly/archive/v%POLLY_VERSION%.tar.gz"
  - cmd: cmake -E tar xf "v%POLLY_VERSION%.tar.gz"
  - cmd: set POLLY_ROOT=%cd%\polly-%POLLY_VERSION%

  # Python 3 for Polly
  - cmd: set PATH=C:\Python34-x64;%PATH%

  # Check versions of tools
  - cmd: where cmake
  - cmd: cmake --version
  - cmd: where python
  - cmd: python --version

build_script:
  - cmd: python .\jenkins.py
