# Windows (https://github.com/travis-ci-tester/toolchain-table)

environment:
  global:
    # This variable used only if '--upload' added to 'jenkins.py'
    GITHUB_USER_PASSWORD:
      secure: KbhVDnegXkjLm8H7lUZX9/t/4AL3dzhQLy8mWZ3Ldv0sXDs7d5bFz7+Yo3EFZNtw

  matrix:
    # Note: 'default' toolchain is the same as 'vs-14-2015'

    # FIXME: https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1927/job/u9txa9wu110nrutw
    #- TOOLCHAIN: "ninja-vs-12-2013-win64"
    #  PROJECT_DIR: examples\SuiteSparse

    # FIXME: https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1927/job/1wbtot8sxxuyug95
    #- TOOLCHAIN: "nmake-vs-12-2013-win64"
    #  PROJECT_DIR: examples\SuiteSparse

    # FIXME: https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1927/job/b9q2uqvmg29utl1e
    #- TOOLCHAIN: "vs-12-2013-win64"
    #  PROJECT_DIR: examples\SuiteSparse

    # FIXME: https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1927/job/pc3w6jntfn4pd5mr
    #- TOOLCHAIN: "vs-12-2013-xp"
    #  PROJECT_DIR: examples\SuiteSparse

    # FIXME: https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1927/job/1x5vdxfs26uip4ai
    #- TOOLCHAIN: "vs-12-2013"
    #  PROJECT_DIR: examples\SuiteSparse

    # FIXME: https://ci.appveyor.com/project/ingenue/hunter/build/1.0.1927/job/hvgw9rbh6qomih6d
    #- TOOLCHAIN: "vs-14-2015"
    #  PROJECT_DIR: examples\SuiteSparse

    - TOOLCHAIN: "vs-14-2015-win64"
      PROJECT_DIR: examples\SuiteSparse
      HUNTER_BINARY_DIR: C:\_hunter_bin

    - TOOLCHAIN: "mingw"
      PROJECT_DIR: examples\SuiteSparse

    - TOOLCHAIN: "msys"
      PROJECT_DIR: examples\SuiteSparse

install:
  # Python 3
  - cmd: set PATH=C:\Python34-x64;C:\Python34-x64\Scripts;%PATH%

  # Install Python package 'requests'
  - cmd: pip install requests

  # Install latest Polly toolchains and scripts
  - cmd: appveyor DownloadFile https://github.com/ruslo/polly/archive/master.zip
  - cmd: 7z x master.zip
  - cmd: set POLLY_ROOT=%cd%\polly-master

  # Install dependencies (CMake, Ninja)
  - cmd: python %POLLY_ROOT%\bin\install-ci-dependencies.py

  # Tune locations
  - cmd: set PATH=%cd%\_ci\cmake\bin;%PATH%
  - cmd: set PATH=%cd%\_ci\ninja;%PATH%

  - cmd: git submodule update --init --recursive

  # Remove entry with sh.exe from PATH to fix error with MinGW toolchain
  # (For MinGW make to work correctly sh.exe must NOT be in your path)
  # * http://stackoverflow.com/a/3870338/2288008
  - cmd: set PATH=%PATH:C:\Program Files\Git\usr\bin;=%

  # Use MinGW from Qt tools because version is higher
  # * http://www.appveyor.com/docs/installed-software#qt
  - cmd: set MINGW_PATH=C:\Qt\Tools\mingw492_32\bin

  # MSYS2 location
  - cmd: set MSYS_PATH=C:\msys64\usr\bin

build_script:
  - cmd: python .\jenkins.py

# http://www.appveyor.com/docs/branches#white-and-blacklisting
# Exclude branch 'pkg.template'. Nothing to build there.
branches:
  except:
    - pkg.template
    - /^pr\..*/
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/
